@jwt =
### Index Action
GET http://localhost:3000/products.json


### Show Action
GET http://localhost:3000/products/2.json



### Create Action
POST http://localhost:3000/products.json
Content-Type: application/json

{   
    "name": "Test.2",
    "price": 2.00,
    "description": "12345678111",
    "inventory": 10,
    "sale": false,
    "supplier_id": 1
}
### Update Action
PATCH http://localhost:3000/products/2.json
Content-Type: application/json

{
    "price": 3.00
}

### Destroy Action
DELETE http://localhost:3000/products/1

# ### Create Image (creates and assigns images to products?)
# POST http://localhost:3000/


### Create Action (User Sign Up)
POST http://localhost:3000/users.json
Content-Type: application/json

{
    "name": "Jayme",
    "email": "Jaymealexander@gmail.com",
    "password": "password",
    "password_confirmation": "password"
}


### Sessions Login Action
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
    "email": "Jaymealexander@gmail.com",
    "password": "password"
}

### Order Create
POST http://localhost:3000/orders
Content-Type: application/json
Authorization: Bearer {{jwt}} 
{
    "product_id": 2,
    "quantity": 5
}


### Order Show
GET http://localhost:3000/orders/1.json
Authorization: Bearer {{jwt}}

### Order Index 
GET http://localhost:3000/orders.json
Authorization: Bearer {{jwt}}


### Cart Create
POST http://localhost:3000/carted.json
Content-Type: application/json

{
    "product_id": 1,
    "quantity": 2,
    "user_id": 1,
    "order_id": 1,
    "status": "purchased"
}


