### Index Action
GET http://localhost:3000/products.json


### Show Action
GET http://localhost:3000/products/4.json


### Create Action
POST http://localhost:3000/products.json
Content-Type: application/json

{   
    "name": "Test",
    "price": -2,
    "description": "12345678111"
}
### Update Action
PATCH http://localhost:3000/products/4.json
Content-Type: application/json

{
    "url": "https://www.digitaltechnologylabs.com/wp-content/uploads/2019/06/01.jpg"
}

### Destroy Action
DELETE http://localhost:3000/products/12