### Index Action
GET http://localhost:3000/products.json


### Show Action
GET http://localhost:3000/products/4.json



### Create Action
POST http://localhost:3000/products.json
Content-Type: application/json

{   
    "name": "Test",
    "price": -2,
    "description": "12345678111"
}
### Update Action
PATCH http://localhost:3000/products/4.json
Content-Type: application/json

{
    "url": "https://www.digitaltechnologylabs.com/wp-content/uploads/2019/06/01.jpg"
}

### Destroy Action
DELETE http://localhost:3000/products/12

# ### Create Image (creates and assigns images to products?)
# POST http://localhost:3000/


### Create Action (User Sign Up)
POST http://localhost:3000/users.json
Content-Type: application/json

{
    "name": "Jayme",
    "email": "Jaymealexander.12@gmail.com",
    "password": "password",
    "password_confirmation": "password"
}


### Sessions Login Action
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
    "email": "Jaymealexander.12@gmail.com",
    "password": "password123"
}

### Order Create
POST http://localhost:3000/orders
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2Njg0NDM2NDd9.k5PsXCKCXr5kIKMXa8HaWZNcAtXtHDUBEwmhJyNhXuY

{
    "user_id": 1,
    "product_id": 11,
    "quantity": 1,
    "subtotal": 200.00,
    "tax":     subtotal * 0.06,
    "total":    subtotal + tax
}


### Order Show
GET http://localhost:3000/orders/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2Njg0NDM2NDd9.k5PsXCKCXr5kIKMXa8HaWZNcAtXtHDUBEwmhJyNhXuY


### Order Index 
GET http://localhost:3000/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2Njg0NDM2NDd9.k5PsXCKCXr5kIKMXa8HaWZNcAtXtHDUBEwmhJyNhXuY


